<?php $__env->startSection('content'); ?>
<section class="spad" style="padding-top:130px;background:#0b0b0b;min-height:70vh;">
<div class="container">
 <div class="section-title text-white"><h2>Music & Videos</h2><p>Search by name, artist, year or album.</p></div>
 <form method="GET" class="row mb-5" style="background:#151515;padding:20px;border-radius:8px;">
  <div class="col-lg-4 mb-2"><input name="search" value="<?php echo e(request('search')); ?>" class="form-control" placeholder="Name / Artist / Album / Year"></div>
  <div class="col-lg-2 mb-2"><select name="type" class="form-control"><option value="">All</option><option value="music" <?php if(request('type')==='music'): echo 'selected'; endif; ?>>Music</option><option value="video" <?php if(request('type')==='video'): echo 'selected'; endif; ?>>Video</option></select></div>
  <div class="col-lg-2 mb-2"><select name="artist" class="form-control"><option value="">Artist</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $artists; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $artist): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option <?php if(request('artist')===$artist): echo 'selected'; endif; ?>><?php echo e($artist); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
  <div class="col-lg-2 mb-2"><select name="album" class="form-control"><option value="">Album</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $albums; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $album): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option <?php if(request('album')===$album): echo 'selected'; endif; ?>><?php echo e($album); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
  <div class="col-lg-2 mb-2"><select name="year" class="form-control"><option value="">Year</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $years; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $year): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option <?php if((string)request('year')===(string)$year): echo 'selected'; endif; ?>><?php echo e($year); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
  <div class="col-12 mt-2"><button class="btn btn-light">Search</button> <a href="<?php echo e(route('media.index')); ?>" class="btn btn-outline-light">Clear</a></div>
 </form>
 <div class="row">
 <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
  <div class="col-lg-3 col-md-6 mb-4"><div style="background:#151515;padding:12px;height:100%;border-radius:8px;position:relative;">
   <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($item->created_at->gte(now()->subDays(7))): ?><span class="new-flash">NEW</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
   <a href="<?php echo e(route('media.show',$item)); ?>"><img src="<?php echo e($item->thumbnail_url ?: asset('users/img/large-item.jpg')); ?>" style="width:100%;height:190px;object-fit:cover;border-radius:6px;"></a>
   <h4 class="text-white mt-3"><?php echo e($item->title); ?></h4><p class="text-muted mb-1"><?php echo e($item->artist ?: 'Unknown Artist'); ?></p><small class="text-muted"><?php echo e($item->album ?: 'Single'); ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($item->year): ?> · <?php echo e($item->year); ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></small>
  </div></div>
 <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?> <div class="col-12 text-white">No results found.</div><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
 </div>
 <div class="mt-3"><?php echo e($items->links()); ?></div>
</div></section>
<style>.new-flash{position:absolute;top:18px;left:18px;background:#ff2b2b;color:#fff;padding:4px 9px;font-size:11px;font-weight:700;border-radius:20px;animation:flashNew .8s infinite alternate}@keyframes flashNew{from{opacity:.35}to{opacity:1}}</style>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('user.layout', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\LAPVY\Downloads\E-Project-Sound-COMPLETE\resources\views/user/media.blade.php ENDPATH**/ ?>